export interface CountryCode {
  code: string;
  flag: string;
  name: string;
  iso: string;
}

export const COUNTRY_CODES: CountryCode[] = [
  // América Latina y Caribe
  { code: "+52", flag: "🇲🇽", name: "México (+52)", iso: "MX" },
  { code: "+1", flag: "🇺🇸", name: "Estados Unidos (+1)", iso: "US" },
  { code: "+1", flag: "🇨🇦", name: "Canadá (+1)", iso: "CA" },
  { code: "+57", flag: "🇨🇴", name: "Colombia (+57)", iso: "CO" },
  { code: "+54", flag: "🇦🇷", name: "Argentina (+54)", iso: "AR" },
  { code: "+56", flag: "🇨🇱", name: "Chile (+56)", iso: "CL" },
  { code: "+51", flag: "🇵🇪", name: "Perú (+51)", iso: "PE" },
  { code: "+593", flag: "🇪🇨", name: "Ecuador (+593)", iso: "EC" },
  { code: "+58", flag: "🇻🇪", name: "Venezuela (+58)", iso: "VE" },
  { code: "+502", flag: "🇬🇹", name: "Guatemala (+502)", iso: "GT" },
  { code: "+503", flag: "🇸🇻", name: "El Salvador (+503)", iso: "SV" },
  { code: "+504", flag: "🇭🇳", name: "Honduras (+504)", iso: "HN" },
  { code: "+505", flag: "🇳🇮", name: "Nicaragua (+505)", iso: "NI" },
  { code: "+506", flag: "🇨🇷", name: "Costa Rica (+506)", iso: "CR" },
  { code: "+507", flag: "🇵🇦", name: "Panamá (+507)", iso: "PA" },
  { code: "+595", flag: "🇵🇾", name: "Paraguay (+595)", iso: "PY" },
  { code: "+598", flag: "🇺🇾", name: "Uruguay (+598)", iso: "UY" },
  { code: "+591", flag: "🇧🇴", name: "Bolivia (+591)", iso: "BO" },
  { code: "+1-787", flag: "🇵🇷", name: "Puerto Rico (+1-787)", iso: "PR" },
  { code: "+1-809", flag: "🇩🇴", name: "Rep. Dominicana (+1-809)", iso: "DO" },
  { code: "+53", flag: "🇨🇺", name: "Cuba (+53)", iso: "CU" },
  { code: "+509", flag: "🇭🇹", name: "Haití (+509)", iso: "HT" },
  { code: "+1-876", flag: "🇯🇲", name: "Jamaica (+1-876)", iso: "JM" },
  { code: "+501", flag: "🇧🇿", name: "Belice (+501)", iso: "BZ" },
  { code: "+592", flag: "🇬🇾", name: "Guyana (+592)", iso: "GY" },
  { code: "+597", flag: "🇸🇷", name: "Surinam (+597)", iso: "SR" },
  { code: "+55", flag: "🇧🇷", name: "Brasil (+55)", iso: "BR" },
  { code: "+1-268", flag: "🇦🇬", name: "Antigua y Barbuda (+1-268)", iso: "AG" },
  { code: "+1-242", flag: "🇧🇸", name: "Bahamas (+1-242)", iso: "BS" },
  { code: "+1-246", flag: "🇧🇧", name: "Barbados (+1-246)", iso: "BB" },
  { code: "+1-767", flag: "🇩🇲", name: "Dominica (+1-767)", iso: "DM" },
  { code: "+1-473", flag: "🇬🇩", name: "Granada (+1-473)", iso: "GD" },
  { code: "+1-869", flag: "🇰🇳", name: "San Cristóbal y Nieves (+1-869)", iso: "KN" },
  { code: "+1-758", flag: "🇱🇨", name: "Santa Lucía (+1-758)", iso: "LC" },
  { code: "+1-784", flag: "🇻🇨", name: "San Vicente y las Granadinas (+1-784)", iso: "VC" },
  { code: "+1-868", flag: "🇹🇹", name: "Trinidad y Tobago (+1-868)", iso: "TT" },
  { code: "+599", flag: "🇨🇼", name: "Curazao (+599)", iso: "CW" },
  { code: "+297", flag: "🇦🇼", name: "Aruba (+297)", iso: "AW" },

  // Europa
  { code: "+34", flag: "🇪🇸", name: "España (+34)", iso: "ES" },
  { code: "+44", flag: "🇬🇧", name: "Reino Unido (+44)", iso: "GB" },
  { code: "+49", flag: "🇩🇪", name: "Alemania (+49)", iso: "DE" },
  { code: "+33", flag: "🇫🇷", name: "Francia (+33)", iso: "FR" },
  { code: "+39", flag: "🇮🇹", name: "Italia (+39)", iso: "IT" },
  { code: "+351", flag: "🇵🇹", name: "Portugal (+351)", iso: "PT" },
  { code: "+31", flag: "🇳🇱", name: "Países Bajos (+31)", iso: "NL" },
  { code: "+32", flag: "🇧🇪", name: "Bélgica (+32)", iso: "BE" },
  { code: "+41", flag: "🇨🇭", name: "Suiza (+41)", iso: "CH" },
  { code: "+43", flag: "🇦🇹", name: "Austria (+43)", iso: "AT" },
  { code: "+46", flag: "🇸🇪", name: "Suecia (+46)", iso: "SE" },
  { code: "+47", flag: "🇳🇴", name: "Noruega (+47)", iso: "NO" },
  { code: "+45", flag: "🇩🇰", name: "Dinamarca (+45)", iso: "DK" },
  { code: "+358", flag: "🇫🇮", name: "Finlandia (+358)", iso: "FI" },
  { code: "+353", flag: "🇮🇪", name: "Irlanda (+353)", iso: "IE" },
  { code: "+30", flag: "🇬🇷", name: "Grecia (+30)", iso: "GR" },
  { code: "+48", flag: "🇵🇱", name: "Polonia (+48)", iso: "PL" },
  { code: "+420", flag: "🇨🇿", name: "República Checa (+420)", iso: "CZ" },
  { code: "+36", flag: "🇭🇺", name: "Hungría (+36)", iso: "HU" },
  { code: "+40", flag: "🇷🇴", name: "Rumania (+40)", iso: "RO" },
  { code: "+359", flag: "🇧🇬", name: "Bulgaria (+359)", iso: "BG" },
  { code: "+385", flag: "🇭🇷", name: "Croacia (+385)", iso: "HR" },
  { code: "+381", flag: "🇷🇸", name: "Serbia (+381)", iso: "RS" },
  { code: "+421", flag: "🇸🇰", name: "Eslovaquia (+421)", iso: "SK" },
  { code: "+386", flag: "🇸🇮", name: "Eslovenia (+386)", iso: "SI" },
  { code: "+370", flag: "🇱🇹", name: "Lituania (+370)", iso: "LT" },
  { code: "+371", flag: "🇱🇻", name: "Letonia (+371)", iso: "LV" },
  { code: "+372", flag: "🇪🇪", name: "Estonia (+372)", iso: "EE" },
  { code: "+356", flag: "🇲🇹", name: "Malta (+356)", iso: "MT" },
  { code: "+357", flag: "🇨🇾", name: "Chipre (+357)", iso: "CY" },
  { code: "+352", flag: "🇱🇺", name: "Luxemburgo (+352)", iso: "LU" },
  { code: "+354", flag: "🇮🇸", name: "Islandia (+354)", iso: "IS" },
  { code: "+376", flag: "🇦🇩", name: "Andorra (+376)", iso: "AD" },
  { code: "+377", flag: "🇲🇨", name: "Mónaco (+377)", iso: "MC" },
  { code: "+378", flag: "🇸🇲", name: "San Marino (+378)", iso: "SM" },
  { code: "+380", flag: "🇺🇦", name: "Ucrania (+380)", iso: "UA" },
  { code: "+375", flag: "🇧🇾", name: "Bielorrusia (+375)", iso: "BY" },
  { code: "+373", flag: "🇲🇩", name: "Moldavia (+373)", iso: "MD" },
  { code: "+355", flag: "🇦🇱", name: "Albania (+355)", iso: "AL" },
  { code: "+389", flag: "🇲🇰", name: "Macedonia del Norte (+389)", iso: "MK" },
  { code: "+387", flag: "🇧🇦", name: "Bosnia y Herzegovina (+387)", iso: "BA" },
  { code: "+382", flag: "🇲🇪", name: "Montenegro (+382)", iso: "ME" },
  { code: "+7", flag: "🇷🇺", name: "Rusia (+7)", iso: "RU" },

  // Asia y Medio Oriente
  { code: "+86", flag: "🇨🇳", name: "China (+86)", iso: "CN" },
  { code: "+81", flag: "🇯🇵", name: "Japón (+81)", iso: "JP" },
  { code: "+82", flag: "🇰🇷", name: "Corea del Sur (+82)", iso: "KR" },
  { code: "+91", flag: "🇮🇳", name: "India (+91)", iso: "IN" },
  { code: "+62", flag: "🇮🇩", name: "Indonesia (+62)", iso: "ID" },
  { code: "+63", flag: "🇵🇭", name: "Filipinas (+63)", iso: "PH" },
  { code: "+84", flag: "🇻🇳", name: "Vietnam (+84)", iso: "VN" },
  { code: "+66", flag: "🇹🇭", name: "Tailandia (+66)", iso: "TH" },
  { code: "+60", flag: "🇲🇾", name: "Malasia (+60)", iso: "MY" },
  { code: "+65", flag: "🇸🇬", name: "Singapur (+65)", iso: "SG" },
  { code: "+886", flag: "🇹🇼", name: "Taiwán (+886)", iso: "TW" },
  { code: "+852", flag: "🇭🇰", name: "Hong Kong (+852)", iso: "HK" },
  { code: "+853", flag: "🇲🇴", name: "Macao (+853)", iso: "MO" },
  { code: "+92", flag: "🇵🇰", name: "Pakistán (+92)", iso: "PK" },
  { code: "+880", flag: "🇧🇩", name: "Bangladesh (+880)", iso: "BD" },
  { code: "+94", flag: "🇱🇰", name: "Sri Lanka (+94)", iso: "LK" },
  { code: "+977", flag: "🇳🇵", name: "Nepal (+977)", iso: "NP" },
  { code: "+971", flag: "🇦🇪", name: "Emiratos Árabes Unidos (+971)", iso: "AE" },
  { code: "+966", flag: "🇸🇦", name: "Arabia Saudita (+966)", iso: "SA" },
  { code: "+972", flag: "🇮🇱", name: "Israel (+972)", iso: "IL" },
  { code: "+90", flag: "🇹🇷", name: "Turquía (+90)", iso: "TR" },
  { code: "+961", flag: "🇱🇧", name: "Líbano (+961)", iso: "LB" },
  { code: "+962", flag: "🇯🇴", name: "Jordania (+962)", iso: "JO" },
  { code: "+965", flag: "🇰🇼", name: "Kuwait (+965)", iso: "KW" },
  { code: "+974", flag: "🇶🇦", name: "Catar (+974)", iso: "QA" },
  { code: "+968", flag: "🇴🇲", name: "Omán (+968)", iso: "OM" },
  { code: "+973", flag: "🇧🇭", name: "Baréin (+973)", iso: "BH" },
  { code: "+964", flag: "🇮🇶", name: "Irak (+964)", iso: "IQ" },
  { code: "+98", flag: "🇮🇷", name: "Irán (+98)", iso: "IR" },
  { code: "+963", flag: "🇸🇾", name: "Siria (+963)", iso: "SY" },
  { code: "+967", flag: "🇾🇪", name: "Yemen (+967)", iso: "YE" },
  { code: "+95", flag: "🇲🇲", name: "Myanmar (+95)", iso: "MM" },
  { code: "+855", flag: "🇰🇭", name: "Camboya (+855)", iso: "KH" },
  { code: "+856", flag: "🇱🇦", name: "Laos (+856)", iso: "LA" },
  { code: "+976", flag: "🇲🇳", name: "Mongolia (+976)", iso: "MN" },
  { code: "+994", flag: "🇦🇿", name: "Azerbaiyán (+994)", iso: "AZ" },
  { code: "+995", flag: "🇬🇪", name: "Georgia (+995)", iso: "GE" },
  { code: "+374", flag: "🇦🇲", name: "Armenia (+374)", iso: "AM" },
  { code: "+7", flag: "🇰🇿", name: "Kazajistán (+7)", iso: "KZ" },
  { code: "+998", flag: "🇺🇿", name: "Uzbekistán (+998)", iso: "UZ" },
  { code: "+996", flag: "🇰🇬", name: "Kirguistán (+996)", iso: "KG" },
  { code: "+992", flag: "🇹🇯", name: "Tayikistán (+992)", iso: "TJ" },
  { code: "+993", flag: "🇹🇲", name: "Turkmenistán (+993)", iso: "TM" },
  { code: "+93", flag: "🇦🇫", name: "Afganistán (+93)", iso: "AF" },

  // África
  { code: "+20", flag: "🇪🇬", name: "Egipto (+20)", iso: "EG" },
  { code: "+27", flag: "🇿🇦", name: "Sudáfrica (+27)", iso: "ZA" },
  { code: "+212", flag: "🇲🇦", name: "Marruecos (+212)", iso: "MA" },
  { code: "+234", flag: "🇳🇬", name: "Nigeria (+234)", iso: "NG" },
  { code: "+254", flag: "🇰🇪", name: "Kenia (+254)", iso: "KE" },
  { code: "+216", flag: "🇹🇳", name: "Túnez (+216)", iso: "TN" },
  { code: "+213", flag: "🇩🇿", name: "Argelia (+213)", iso: "DZ" },
  { code: "+251", flag: "🇪🇹", name: "Etiopía (+251)", iso: "ET" },
  { code: "+233", flag: "🇬🇭", name: "Ghana (+233)", iso: "GH" },
  { code: "+225", flag: "🇨🇮", name: "Costa de Marfil (+225)", iso: "CI" },
  { code: "+221", flag: "🇸🇳", name: "Senegal (+221)", iso: "SN" },
  { code: "+255", flag: "🇹🇿", name: "Tanzania (+255)", iso: "TZ" },
  { code: "+256", flag: "🇺🇬", name: "Uganda (+256)", iso: "UG" },
  { code: "+237", flag: "🇨🇲", name: "Camerún (+237)", iso: "CM" },
  { code: "+244", flag: "🇦🇴", name: "Angola (+244)", iso: "AO" },
  { code: "+258", flag: "🇲🇿", name: "Mozambique (+258)", iso: "MZ" },
  { code: "+263", flag: "🇿🇼", name: "Zimbabue (+263)", iso: "ZW" },
  { code: "+260", flag: "🇿🇲", name: "Zambia (+260)", iso: "ZM" },
  { code: "+243", flag: "🇨🇩", name: "Congo (RD) (+243)", iso: "CD" },
  { code: "+242", flag: "🇨🇬", name: "Congo (+242)", iso: "CG" },
  { code: "+250", flag: "🇷🇼", name: "Ruanda (+250)", iso: "RW" },
  { code: "+257", flag: "🇧🇮", name: "Burundi (+257)", iso: "BI" },
  { code: "+261", flag: "🇲🇬", name: "Madagascar (+261)", iso: "MG" },

  // Oceanía
  { code: "+61", flag: "🇦🇺", name: "Australia (+61)", iso: "AU" },
  { code: "+64", flag: "🇳🇿", name: "Nueva Zelanda (+64)", iso: "NZ" },
  { code: "+675", flag: "🇵🇬", name: "Papúa Nueva Guinea (+675)", iso: "PG" },
  { code: "+679", flag: "🇫🇯", name: "Fiyi (+679)", iso: "FJ" },
  { code: "+685", flag: "🇼🇸", name: "Samoa (+685)", iso: "WS" },
  { code: "+676", flag: "🇹🇴", name: "Tonga (+676)", iso: "TO" },
  { code: "+678", flag: "🇻🇺", name: "Vanuatu (+678)", iso: "VU" },
  { code: "+686", flag: "🇰🇮", name: "Kiribati (+686)", iso: "KI" },
  { code: "+691", flag: "🇫🇲", name: "Micronesia (+691)", iso: "FM" },
  { code: "+692", flag: "🇲🇭", name: "Islas Marshall (+692)", iso: "MH" },
  { code: "+680", flag: "🇵🇼", name: "Palaos (+680)", iso: "PW" },
  { code: "+677", flag: "🇸🇧", name: "Islas Salomón (+677)", iso: "SB" }
];
